-- 查看H2数据库中的所有表
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PUBLIC';

-- 查看slow_query_template表结构
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SLOW_QUERY_TEMPLATE';

-- 查看slow_query_sample表结构
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SLOW_QUERY_SAMPLE';

-- 查看索引信息
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME IN ('SLOW_QUERY_TEMPLATE', 'SLOW_QUERY_SAMPLE');
